---

- hosts: local
  gather_facts: yes
#  become: yes
  vars_files:
    - ./vars/internal_vars.yml
  pre_tasks:
    - name: Import prereq
      import_tasks: ./roles/__prereq/tasks/main.yml
      tags:
        - always

  post_tasks:
    - name: Import postreq
      import_tasks: ./roles/__postreq/tasks/main.yml
      tags:
        - always
  roles:
    - role: aliases
      tags:
        - aliases
      description: Installs a handful command line aliases

    - role: asdf
      tags:
        - asdf
      description: Installs asdf, which a tool version manager

    - role: homebrew
      tags:
        - homebrew
      description: Installs and configures homebrew

    - role: docker
      tags:
        - docker
        - cloud-tools
      description: Installs and configures docker and some related tooling

    - role: terraform
      tags:
        - terraform
        - cloud-tools
      description: Installs and configures Terraform

    - role: aws
      tags:
        - aws
        - cloud-tools
      description: Instals and configures awscli

    - role: python
      tags:
        - python
        - programming-languages
      description: Installs and configures the python programming language

    - role: nodejs
      tags:
        - nodejs
        - programming-languages
      description: Installs and configures nodejs
