---

- name: Ensure Go asdf plugin dependencies are installed
  community.general.homebrew:
    name:
    - gpg
    - gawk
    - coreutils

---

- name: Check if asdf plugin list has {{ plugin }}
  shell: asdf plugin list | grep {{ plugin }}
  register: has_plugin
  failed_when: has_plugin.rc > 1

- name: Install {{ plugin }} asdf plugin
  shell: asdf plugin add {{ plugin }} {{ plugin_path if plugin_path else '' }}
  when: has_plugin.rc == 1

- name: Install {{ plugin }} version {{ version }}
  shell: asdf install {{ plugin }} {{ version }}

- name: Set Global version of {{ plugin }}
  shell: asdf global {{ plugin }} {{ version }}


# TODO Should I have some alias for this?
# https://github.com/kennyp/asdf-golang#when-using-go-get-or-go-install