---

- name: Check if XCode Command Line Tools are installed
  shell: xcode-select -p
  register: xcode_check_result

- name: Install XCode Command Line Tools
  shell: xcode-select --install
  when: xcode_check_result.rc == 1

- name: Install Python Build Environment Tools
  community.general.homebrew:
    update_homebrew: yes
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib

- name: Check if asdf plugin list has {{ plugin }}
  shell: asdf plugin list | grep {{ plugin }}
  register: has_plugin
  failed_when: has_plugin.rc > 1

- name: Install {{ plugin }} asdf plugin
  shell: asdf plugin add {{ plugin }} {{ plugin_path if plugin_path else '' }}
  when: has_plugin.rc == 1

- name: Install {{ plugin }} version {{ version }}
  shell: asdf install {{ plugin }} {{ version }}

- name: Set Global version of {{ plugin }}
  shell: asdf global {{ plugin }} {{ version }}

